/**
 * The 48 numeric/text `.wdr` keys in WinISD's OWN file order, each with the value WinISD
 * writes when nothing is set. Source of truth: `drivers/sample/winisd/john-all-defaults.wdr`
 * (New → Save, nothing typed).
 */
export const INI_ROWS: ReadonlyArray<string> = [
    'Qts',
    'Znom',
    'Fs',
    'Pe',
    'SPL',
    'Re',
    'Le',
    'fLe',
    'KLe',
    'BL',
    'Xmax',
    'Cms',
    'Qms',
    'Qes',
    'Rms',
    'Mms',
    'Sd',
    'Vas',
    'Dia',
    'Vd',
    'no',
    'Dd',
    'EBP',
    'numVC',
    'Hc',
    'Hg',
    'SPLmax',
    'SPLmaxLF',
    'USPL',
    'alfaVC',
    'Rt',
    'Ct',
    'gamma',
    'Rme',
    'Mpow',
    'Mcost',
    'Gloss',
    'VCCon',
    'c',
    'roo',
    'Thick',
    'Depth',
    'MagDepth',
    'Magnet',
    'Basket',
    'Outer',
    'Vcd',
    'DVol',
];

