/**
 * The `.wdr` Comment= field holds the driver's SOURCE URL (John's ruling, winisd_tools
 * BUG_20260822 and BUG_20260824), and an incoming Comment survives the round trip unchanged.
 * bugs/BUG_20261007_wdr-comment-lost-on-round-trip.md
 */
import {describe, expect, it} from 'vitest';
import {createEngine} from '../../engine/index.js';
import {WinIsdDriverConverter} from '../../domain/winIsdDriverConverter.js';
import {WINISD_NEWLINE_SENTINEL} from '../../winisd/index.js';
import {driverFromSpec} from '../fixtures/recordBuilders.js';

const engine = createEngine();

function commentOf(wdr: string): string {
  const line = wdr.split(/\r?\n/).find(l => l.startsWith('Comment='));
  return (line ?? '').slice('Comment='.length).replaceAll(WINISD_NEWLINE_SENTINEL, '\n');
}

/** A driver record in yml; `sources` and `comment` are the two things these tests vary. */
function recordYml(sources: string, comment: string, specs = 'woofer: {}'): string {
  return `
uuid: {value: 00000000-0000-4000-8000-000000000000}
quality: {confirmed_fields: [], fields_with_issues: [], missing: [], invalid: [], parse_errors: [], cross_source_only: []}
manufacturer: {value: Acme, origin: entered}
brand: {value: Acme, origin: entered}
model: {value: Widget, origin: entered}
sku: {value: acme-widget, grounds: [{origin: entered, reading: acme-widget}]}
driver_type: {value: woofer, origin: entered}
data_sources: {value: ${sources}}
provided_by: {value: '', origin: entered}
comment: {value: '${comment}', origin: entered}
added: {value: '2026-09-01', origin: entered}
specs:
  ${specs}
`;
}

function wdrFromYml(yml: string): string {
  const {wdr, errors} = new WinIsdDriverConverter(engine).driverYmlToOpenisdAndWdr(yml);
  if (wdr === null) throw new Error(errors.map(e => e.message).join('; '));
  return wdr;
}

const QES_WITH_DQ = `woofer:
    Qts:
      readings: {manual: {read_value: 1.5}}
      dq_scraper:
        - {kind: range, severity: error, rule: range-above-max, params: {field: Qts, value: 1.5, limit: 0.8, unit: ''}, detail: 'Qts=1.5 above max 0.8'}`;

describe('.wdr Comment=', () => {
  it('keeps an incoming Comment byte-identical through import and export, line breaks included', () => {
    const base = driverFromSpec(engine, {Fs_hz: 30, Qes: 0.4, Qms: 4, Re_ohm: 6.4, Sd_m2: 0.0132}).toWdrIniText().value!;
    const incoming = `first 111111${WINISD_NEWLINE_SENTINEL}second 222222 `;
    const withIncoming = base.replace(/^Comment=.*$/m, `Comment=${incoming}`);

    const imported = new WinIsdDriverConverter(engine).winIsdDriverToOpenIsdDriver(withIncoming);
    if (imported.value === null) throw new Error(imported.errors.map(e => e.message).join('; '));
    const exported = imported.value.toWdrIniText().value!;

    expect(commentOf(exported)).toBe('first 111111\nsecond 222222 ');
  });

  it('writes the manufacturer datasheet URL when there is no incoming Comment', () => {
    const wdr = wdrFromYml(recordYml(
      '{manufacturer_product_page: "http://p.invalid/1", manufacturer_datasheet: "http://d.invalid/2"}', ''));
    expect(commentOf(wdr)).toBe('http://d.invalid/2');
  });

  it('falls back to the first source URL when there is no datasheet', () => {
    const wdr = wdrFromYml(recordYml('{manufacturer_listing_page: "http://l.invalid/3", manufacturer_product_page: "http://p.invalid/1"}', ''));
    expect(commentOf(wdr)).toBe('http://p.invalid/1');
  });

  it('keeps the [DQ] suffix after the URL', () => {
    const wdr = wdrFromYml(recordYml('{manufacturer_datasheet: "http://d.invalid/2"}', '', QES_WITH_DQ));
    expect(commentOf(wdr).split('\n')[0]).toBe('http://d.invalid/2');
    expect(commentOf(wdr)).toMatch(/\n\[DQ\] Qts=1.5: Qts=1.5 above max 0.8/);
  });

  it('is empty with no incoming Comment, no URL and no notes, never "Generated by OpenIsd"', () => {
    expect(commentOf(wdrFromYml(recordYml('{}', '')))).toBe('');
  });
});
