/**
 * The runtime-generated sample project (`sample-project.owpr`) — ONE shared path + generator.
 *
 * It is generated by `generateSample.ts` into the **git-ignored `build/test-fixtures/` dir**,
 * never into the tree: a generated fixture must not be committed (CLAUDE.md "UI Tests &
 * Fixtures"). Every consumer reads it through `SAMPLE_PROJECT_OWPR` / `readSampleProject()` so
 * the location is single-sourced instead of a per-spec `join('..','fixtures', …)` that breaks
 * the moment the file moves.
 */
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

/** Absolute path of the generated sample project, inside the ignored `build/` dir. */
export const SAMPLE_PROJECT_OWPR = join(
  dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..', 'build', 'test-fixtures', 'sample-project.owpr');

/** Generate the sample project on first use (idempotent), then return its path. */
export function ensureSampleProject(): string {
  if (!existsSync(SAMPLE_PROJECT_OWPR)) {
    execSync('npx vite-node ' + join(dirname(fileURLToPath(import.meta.url)), 'generateSample.ts'), { stdio: 'inherit' });
  }
  return SAMPLE_PROJECT_OWPR;
}

/** The sample project's bytes, generating it first if needed. */
export function readSampleProject(): Buffer {
  return readFileSync(ensureSampleProject());
}