/**
 * The runtime-generated sample project (`sample-project.owpr`) — ONE shared path + generator.
 *
 * It is generated by `generateSample.ts` into the **git-ignored `build/test-fixtures/` dir**,
 * never into the tree: a generated fixture must not be committed (CLAUDE.md "UI Tests &
 * Fixtures"). Every consumer reads it through `SAMPLE_PROJECT_OWPR` / `readSampleProject()` so
 * the location is single-sourced instead of a per-spec `join('..','fixtures', …)` that breaks
 * the moment the file moves.
 */
import {existsSync, readFileSync, statSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execSync} from 'node:child_process';

/** Absolute path of the generated sample project, inside the ignored `build/` dir. */
export const SAMPLE_PROJECT_OWPR = join(
  dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..', 'build', 'test-fixtures', 'sample-project.owpr');

/** Absolute path of the generated complete driver project, inside the ignored `build/` dir. */
export const COMPLETE_DRIVER_PROJECT_OWPR = join(
  dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..', 'build', 'test-fixtures', 'complete-driver-project.owpr');

const HERE = dirname(fileURLToPath(import.meta.url));

/** What the generated files are made from: the generator itself and the project schema. A change
 *  to either makes the cached files stale — they were written under the old shape. */
const GENERATED_FROM = [
  join(HERE, 'generateSample.ts'),
  join(HERE, '..', '..', '..', 'design', 'domain', 'openisdSchema.ts'),
];

/** Whether `output` is missing or older than anything it is generated from. */
function isStale(output: string): boolean {
  if (!existsSync(output)) return true;
  const built = statSync(output).mtimeMs;
  return GENERATED_FROM.some(source => statSync(source).mtimeMs > built);
}

/** Generate the sample projects when missing or stale, then return SAMPLE_PROJECT_OWPR path. */
export function ensureSampleProject(): string {
  if (isStale(SAMPLE_PROJECT_OWPR) || isStale(COMPLETE_DRIVER_PROJECT_OWPR)) {
    execSync('npx vite-node ' + join(dirname(fileURLToPath(import.meta.url)), 'generateSample.ts'), { stdio: 'inherit' });
  }
  return SAMPLE_PROJECT_OWPR;
}

/** Ensure complete driver project exists and return its path. */
export function ensureCompleteDriverProject(): string {
  ensureSampleProject();
  return COMPLETE_DRIVER_PROJECT_OWPR;
}

/** The sample project's bytes, generating it first if needed. */
export function readSampleProject(): Buffer {
  return readFileSync(ensureSampleProject());
}

/** The complete driver project's bytes, generating it first if needed. */
export function readCompleteDriverProject(): Buffer {
  return readFileSync(ensureCompleteDriverProject());
}